version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shortener-url-serverless-golang"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5790744a"
s3_prefix = "shortener-url-serverless-golang"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
